# Generated by Django 2.2.6 on 2019-10-13 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardHolder', models.CharField(max_length=100)),
                ('accountNotes', models.TextField(help_text='Enter a brief description of the account', max_length=1000)),
                ('accountNumber', models.CharField(max_length=13)),
                ('pin', models.CharField(max_length=4)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Account')),
            ],
        ),
    ]
