# Generated by Django 2.2.6 on 2019-11-05 03:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='accountNotes',
        ),
        migrations.RemoveField(
            model_name='card',
            name='accountNumber',
        ),
        migrations.RemoveField(
            model_name='card',
            name='cardHolder',
        ),
        migrations.RemoveField(
            model_name='card',
            name='id',
        ),
        migrations.AddField(
            model_name='account',
            name='accountName',
            field=models.CharField(default='none', help_text='Enter the name of the account holder', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.CharField(max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='phoneNumber',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='cardNumber',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='Unique Id for this card', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='card',
            name='dateOfIssue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='expiryDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('v', 'Valid'), ('e', 'Expired'), ('s', 'Lost/Stolen')], default='m', help_text='CARD_Status', max_length=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='accountNumber',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular account', primary_key=True, serialize=False),
        ),
    ]
