# Generated by Django 2.2.6 on 2019-10-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_account_accountholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountHolder',
            field=models.CharField(help_text='Enter the name of the account holder', max_length=30),
        ),
    ]
