# Generated by Django 2.2.7 on 2019-11-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20191106_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, null=True)),
                ('lastRefillDate', models.DateField(blank=True, null=True)),
                ('currentBalance', models.CharField(max_length=22, null=True)),
            ],
        ),
    ]
