# Generated by Django 2.2.7 on 2019-11-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_atm'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'Opeartional')], default='m', help_text='Atm status', max_length=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('v', 'Valid'), ('e', 'Expired'), ('s', 'Lost/Stolen')], default='m', help_text='Card status', max_length=1),
        ),
    ]
