# Generated by Django 2.2.6 on 2019-11-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20191109_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardhistory',
            name='Name',
        ),
        migrations.AddField(
            model_name='cardhistory',
            name='history',
            field=models.TextField(max_length=22, null=True),
        ),
    ]
