# Generated by Django 2.2.6 on 2019-11-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20191109_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardhistory',
            name='history',
            field=models.TextField(default=' ', max_length=22, null=True),
        ),
    ]
