# Generated by Django 2.2.6 on 2019-10-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20191015_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountName',
            field=models.CharField(help_text='Enter the name of the account holder', max_length=30, unique=True),
        ),
    ]
