# Generated by Django 2.2.6 on 2019-11-05 02:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20191104_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='uniqueNum',
        ),
        migrations.AddField(
            model_name='account',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
